### ISSUE TITLE
cannot compile on haiku 64biit

### ISSUE THREAD

**Issue by mazbrili** [HaikuArchives/BSnow#2]
error compile on haiku64 bit..

> snowview.cpp:312 call of overloaded  ... is ambigous

thanks

**Comment by mmuman** [comment]
Ah, I don't have a 64bit install for now… I'll try something.

**Comment by mmuman** [comment]
Ugh, I sid this *might* fix… oh well…

**Comment by mmuman** [comment]
Can you confirm this fixed it?

**Comment by mmuman** [comment]
Seems there are [other issues](https://build.haiku-os.org/buildmaster/master/x86_64/?buildrunDir=4730&viewMode=expanded).

**Comment by mazbrili** [comment]
> Ugh, I sid this _might_ fix… oh well…

sorry not replying long time.. i lockdown  not touch this pc about 1 month and now  first day i use it again.. sorry for that

**Comment by thaflo** [comment]
It's not compiling yet.

`~/BSnow> make 
cc -o "objects.x86_64-cc8-release/BSnow"        objects.x86_64-cc8-release/Flakes.o objects.x86_64-cc8-release/SnowApp.o objects.x86_64-cc8-release/SnowView.o  -Xlinker -soname=_APP_  -L./  -Lobjects.x86_64-cc8-release/    -lbe  -ltracker  -ltranslation  -llocalestub 
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/8.3.0/../../../../x86_64-unknown-haiku/bin/ld: objects.x86_64-cc8-release/SnowApp.o: in function `main':
SnowApp.cpp:(.text.startup+0x81): undefined reference to `operator new(unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/8.3.0/../../../../x86_64-unknown-haiku/bin/ld: SnowApp.cpp:(.text.startup+0xae): undefined reference to `operator new(unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/8.3.0/../../../../x86_64-unknown-haiku/bin/ld: objects.x86_64-cc8-release/SnowView.o: in function `SnowView::AttachedToWindow()':
SnowView.cpp:(.text+0x111): undefined reference to `__dynamic_cast'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/8.3.0/../../../../x86_64-unknown-haiku/bin/ld: SnowView.cpp:(.text+0x22e): undefined reference to `operator new(unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/8.3.0/../../../../x86_64-unknown-haiku/bin/ld: SnowView.cpp:(.text+0x2c4): undefined reference to `operator new(unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/8.3.0/../../../../x86_64-unknown-haiku/bin/ld: SnowView.cpp:(.text+0x2ff): undefined reference to `operator new(unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/8.3.0/../../../../x86_64-unknown-haiku/bin/ld: SnowView.cpp:(.text+0x454): undefined reference to `__dynamic_cast'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/8.3.0/../../../../x86_64-unknown-haiku/bin/ld: objects.x86_64-cc8-release/SnowView.o: in function `SnowView::SnowView()':
SnowView.cpp:(.text+0xca3): undefined reference to `operator new(unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/8.3.0/../../../../x86_64-unknown-haiku/bin/ld: objects.x86_64-cc8-release/SnowView.o: in function `SnowView::SnowView(BMessage*)':
SnowView.cpp:(.text+0xdeb): undefined reference to `operator new[](unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/8.3.0/../../../../x86_64-unknown-haiku/bin/ld: SnowView.cpp:(.text+0xe63): undefined reference to `operator new(unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/8.3.0/../../../../x86_64-unknown-haiku/bin/ld: SnowView.cpp:(.text+0xec1): undefined reference to `operator new(unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/8.3.0/../../../../x86_64-unknown-haiku/bin/ld: objects.x86_64-cc8-release/SnowView.o: in function `SnowView::Instantiate(BMessage*)':
SnowView.cpp:(.text+0xf60): undefined reference to `operator new(unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/8.3.0/../../../../x86_64-unknown-haiku/bin/ld: objects.x86_64-cc8-release/SnowView.o: in function `SnowView::MessageReceived(BMessage*)':
SnowView.cpp:(.text+0x1f76): undefined reference to `operator new(unsigned long)'
collect2: error: ld returned 1 exit status
/boot/system/develop/etc/makefile-engine:249: recipe for target 'objects.x86_64-cc8-release/BSnow' failed
make: *** [objects.x86_64-cc8-release/BSnow] Error 1`

**Comment by OscarL** [comment]
I think this might actually get fixed by #4.

The makefile is using "cc -o" for the final compilation step, that's gcc, and thus it needs to be told to link to `$STDCPPLIBS` (unlike g++, that will do it on its own).

Sneaky typo :-)
